const { supabaseUrl, supabaseKey, storageBucket } = window.AQUERIS_CONFIG;
const db = supabase.createClient(supabaseUrl, supabaseKey);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let authMode='login', products=[], editing=null;
function msg(el,text,type=''){el.textContent=text||'';el.className=`form-message ${type}`;}
function slugify(v){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function money(v){return v==null?'—':`S/${Number(v).toFixed(2)}`;}
async function isAdmin(){const {data,error}=await db.rpc('is_admin');return !error&&!!data;}
async function route(){const {data:{session}}=await db.auth.getSession();$('#auth-view').classList.toggle('hidden',!!session);if(!session){$('#claim-view').classList.add('hidden');$('#dashboard').classList.add('hidden');return;}const admin=await isAdmin();$('#claim-view').classList.toggle('hidden',admin);$('#dashboard').classList.toggle('hidden',!admin);if(admin)await loadDashboard();}
$$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>{authMode=b.dataset.authTab;$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#auth-password').autocomplete=authMode==='login'?'current-password':'new-password';msg($('#auth-message'),'');}));
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const email=$('#auth-email').value.trim(),password=$('#auth-password').value;msg($('#auth-message'),'Procesando...');const res=authMode==='login'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});if(res.error)return msg($('#auth-message'),res.error.message,'error');if(authMode==='signup'&&!res.data.session)return msg($('#auth-message'),'Cuenta creada. Revisa tu correo para confirmar el email y luego inicia sesión.','success');msg($('#auth-message'),'Acceso correcto.','success');await route();});
$('#claim-form').addEventListener('submit',async e=>{e.preventDefault();msg($('#claim-message'),'Validando...');const {data,error}=await db.rpc('claim_admin',{p_code:$('#claim-code').value});if(error||!data)return msg($('#claim-message'),error?.message||'Código inválido o ya utilizado.','error');msg($('#claim-message'),'Administrador activado.','success');await route();});
async function logout(){await db.auth.signOut();location.reload();}$('#logout').addEventListener('click',logout);$('#logout-claim').addEventListener('click',logout);
async function loadDashboard(){await Promise.all([loadProducts(),loadSettings()]);}
async function loadProducts(){const {data,error}=await db.from('products').select('*').order('sort_order').order('name');if(error)return console.error(error);products=data||[];renderProducts();}
function renderProducts(){const q=$('#admin-search').value.trim().toLowerCase(),list=products.filter(p=>!q||`${p.name} ${p.category}`.toLowerCase().includes(q));$('#admin-products').innerHTML=list.map(p=>`<article class="admin-row"><div><strong>${p.name}</strong><span>${p.category} · ${money(p.unit_price)} ${p.active?'· Activo':'· Oculto'}</span></div><div><button class="text-button" data-edit="${p.id}">Editar</button><button class="text-button danger" data-delete="${p.id}">Eliminar</button></div></article>`).join('');$('#stat-total').textContent=products.length;$('#stat-active').textContent=products.filter(p=>p.active).length;$('#stat-featured').textContent=products.filter(p=>p.featured).length;$$('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete));}
$('#admin-search').addEventListener('input',renderProducts);$('#new-product').onclick=()=>{resetEditor();$('#name').focus();};$('#cancel-edit').onclick=resetEditor;$('#name').addEventListener('input',()=>{if(!editing)$('#slug').value=slugify($('#name').value);});
function resetEditor(){editing=null;$('#product-form').reset();$('#brand').value='Don Salvattore';$('#case-label').value='Caja';$('#service-temp').value='14°C a 16°C';$('#active').checked=true;$('#sort-order').value=products.length+1;$('#editor-title').textContent='Nuevo producto';$('#cancel-edit').classList.add('hidden');msg($('#product-message'),'');}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editing=p;$('#product-id').value=p.id;$('#name').value=p.name;$('#slug').value=p.slug;$('#category').value=p.category;$('#brand').value=p.brand;$('#unit-price').value=p.unit_price??'';$('#case-price').value=p.case_price??'';$('#case-label').value=p.case_label||'Caja';$('#service-temp').value=p.service_temp||'';$('#description').value=p.description||'';$('#image-path').value=p.image_path||'';$('#featured').checked=p.featured;$('#active').checked=p.active;$('#sort-order').value=p.sort_order||0;$('#editor-title').textContent=`Editar: ${p.name}`;$('#cancel-edit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'});}
async function uploadImage(file,slug){if(!file)return $('#image-path').value.trim()||null;if(file.size>5*1024*1024)throw new Error('La imagen supera 5 MB.');const ext=file.name.split('.').pop().toLowerCase(),path=`${slug}-${Date.now()}.${ext}`;const {error}=await db.storage.from(storageBucket).upload(path,file,{cacheControl:'3600'});if(error)throw error;return path;}
$('#product-form').addEventListener('submit',async e=>{e.preventDefault();msg($('#product-message'),'Guardando...');try{const slug=$('#slug').value.trim()||slugify($('#name').value),image_path=await uploadImage($('#image-file').files[0],slug);const payload={name:$('#name').value.trim(),slug,category:$('#category').value.trim(),brand:$('#brand').value.trim(),description:$('#description').value.trim(),service_temp:$('#service-temp').value.trim(),unit_price:$('#unit-price').value?Number($('#unit-price').value):null,case_price:$('#case-price').value?Number($('#case-price').value):null,case_label:$('#case-label').value.trim()||'Caja',image_path,featured:$('#featured').checked,active:$('#active').checked,sort_order:Number($('#sort-order').value)||0};const q=editing?db.from('products').update(payload).eq('id',editing.id):db.from('products').insert(payload),{error}=await q;if(error)throw error;resetEditor();await loadProducts();msg($('#product-message'),'Producto guardado.','success');}catch(err){msg($('#product-message'),err.message||'No se pudo guardar.','error');}});
async function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`¿Eliminar "${p.name}"? Esta acción no se puede deshacer.`))return;const {error}=await db.from('products').delete().eq('id',id);if(error)return alert(error.message);if(p.image_path&&!/^https?:\/\//.test(p.image_path)&&!p.image_path.startsWith('assets/'))await db.storage.from(storageBucket).remove([p.image_path]);await loadProducts();if(editing?.id===id)resetEditor();}
async function loadSettings(){const {data,error}=await db.from('site_settings').select('*').eq('id',1).single();if(error||!data)return;$('#setting-name').value=data.business_name;$('#setting-whatsapp').value=data.whatsapp;$('#setting-instagram').value=data.instagram;$('#setting-attention').value=data.attention;$('#setting-location').value=data.location;$('#setting-hero-title').value=data.hero_title;$('#setting-hero-subtitle').value=data.hero_subtitle;}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();msg($('#settings-message'),'Guardando...');const payload={business_name:$('#setting-name').value.trim(),whatsapp:$('#setting-whatsapp').value.replace(/\D/g,''),instagram:$('#setting-instagram').value.trim(),attention:$('#setting-attention').value.trim(),location:$('#setting-location').value.trim(),hero_title:$('#setting-hero-title').value.trim(),hero_subtitle:$('#setting-hero-subtitle').value.trim()};const {error}=await db.from('site_settings').update(payload).eq('id',1);msg($('#settings-message'),error?error.message:'Datos actualizados.',error?'error':'success');});
db.auth.onAuthStateChange(()=>setTimeout(route,0));resetEditor();route();
