const { supabaseUrl, supabaseKey, storageBucket } = window.AQUERIS_CONFIG;
const db = supabase.createClient(supabaseUrl, supabaseKey);
const state = { products: [], settings: null, category: 'Todos', search: '' };
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
function money(v){ return v == null ? 'Consultar' : `S/${Number(v).toFixed(2)}`; }
function imageUrl(path){ if(!path) return ''; if(/^https?:\/\//i.test(path)) return path; if(path.startsWith('assets/')) return `./${path}`; return db.storage.from(storageBucket).getPublicUrl(path).data.publicUrl; }
function whatsappUrl(product){ const n=state.settings?.whatsapp||'51967539019'; const text=product?`Hola Reserva Aqueris, quisiera consultar por ${product.name} (${money(product.unit_price)} unidad).`:'Hola Reserva Aqueris, quisiera consultar por sus vinos y disponibilidad.'; return `https://wa.me/${n}?text=${encodeURIComponent(text)}`; }
function hydrateWhatsApp(){ $$('[data-whatsapp]').forEach(a=>{a.href=whatsappUrl();a.target='_blank';a.rel='noopener';}); }
function card(p){ const img=imageUrl(p.image_path); return `<article class="product-card"><button class="product-media" data-open="${p.id}" aria-label="Ver ${p.name}">${img?`<img src="${img}" alt="${p.name}" loading="lazy" onerror="this.remove();this.parentElement.classList.add('no-image')">`:'<div class="image-placeholder">Reserva Aqueris</div>'}${p.featured?'<span class="badge">Destacado</span>':''}</button><div class="product-copy"><div><span class="category">${p.category}</span><h3>${p.name}</h3></div><p>${p.description||''}</p><div class="prices"><strong>${money(p.unit_price)} <small>unidad</small></strong>${p.case_price!=null?`<span>${money(p.case_price)} · ${p.case_label}</span>`:''}</div><div class="card-actions"><button class="btn btn-ghost" data-open="${p.id}">Detalles</button><a class="btn btn-whatsapp" href="${whatsappUrl(p)}" target="_blank" rel="noopener">Consultar</a></div></div></article>`; }
function render(){ const q=state.search.trim().toLowerCase(); const list=state.products.filter(p=>(state.category==='Todos'||p.category===state.category)&&(!q||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q))); $('#products').innerHTML=list.map(card).join(''); $('#empty').classList.toggle('hidden',list.length>0); $$('[data-open]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.open))); }
function renderFilters(){ const cats=['Todos',...new Set(state.products.map(p=>p.category))]; $('#filters').innerHTML=cats.map(c=>`<button class="filter ${c===state.category?'active':''}" data-category="${c}">${c}</button>`).join(''); $$('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;renderFilters();render();})); }
function openProduct(id){ const p=state.products.find(x=>x.id===id); if(!p)return; const img=imageUrl(p.image_path); $('#modal-content').innerHTML=`<div class="modal-grid"><div class="modal-image">${img?`<img src="${img}" alt="${p.name}" onerror="this.remove()">`:'<div class="image-placeholder">Reserva Aqueris</div>'}</div><div class="modal-copy"><span class="category">${p.category}</span><h2>${p.name}</h2><p>${p.description||''}</p><dl><div><dt>Marca</dt><dd>${p.brand}</dd></div><div><dt>Servicio</dt><dd>${p.service_temp}</dd></div></dl><div class="modal-prices"><strong>${money(p.unit_price)} <small>unidad</small></strong>${p.case_price!=null?`<span>${money(p.case_price)} · ${p.case_label}</span>`:''}</div><a class="btn btn-whatsapp btn-large" href="${whatsappUrl(p)}" target="_blank" rel="noopener">Consultar este producto</a></div></div>`; $('#product-modal').showModal(); }
async function load(){ const [{data:products,error:pErr},{data:settings,error:sErr}]=await Promise.all([db.from('products').select('*').order('sort_order').order('name'),db.from('site_settings').select('*').eq('id',1).single()]); if(pErr)console.error(pErr);else state.products=products||[]; if(!sErr&&settings){state.settings=settings;$('#hero-title').textContent=settings.hero_title;$('#hero-subtitle').textContent=settings.hero_subtitle;$('#location').textContent=settings.location;$('#instagram').textContent=settings.instagram;} const featured=state.products.find(p=>p.featured)||state.products[0]; if(featured)$('#featured-mini').innerHTML=`<span>${featured.category}</span><strong>${featured.name}</strong><small>Desde ${money(featured.unit_price)}</small>`; $('#featured-mini').classList.remove('skeleton'); hydrateWhatsApp();renderFilters();render(); }
$('#search').addEventListener('input',e=>{state.search=e.target.value;render();}); $('#product-modal').addEventListener('click',e=>{if(e.target===$('#product-modal'))$('#product-modal').close();}); $('[data-close]').addEventListener('click',()=>$('#product-modal').close()); $('#year').textContent=new Date().getFullYear(); load();
